config/routes.rb
Rails.application.routes.draw do

  get 'control' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 10
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please! Authorize!"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:new, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(:page => params[:page]).order("id DESC")

    respond_to do |format|
      format.html
      format.xml {render :xml => @posts}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @users = User.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :date, :image_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      redirect_to login_url, alert: "Login/password not found!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path, notice: "Session close"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User #{@user.name} was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User #{@user.name} was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IT::Sheets - @toywar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Lato:400,700'>
  <link href='http://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

  <script>
    function facechange (objName) {
        if ($(objName).css('display') == 'none'){
            $(objName).animate({height: 'show'}, 400);
        }
        else {
            $(objName).animate({height: 'hide'}, 200);
        }
    };
  </script>
  <%= csrf_meta_tags %>
</head>

<%= render 'posts/header' %>

<body class='<%= controller.controller_name %>' >

<%= yield %>

</body>

<%= render 'posts/footer' %>

app/views/posts/_footer.html.erb
<hr class="footer"/>
<div class="footer-pos">
    Follow me <a target="_blank" href="https://twitter.com/toywar" class="footer-icons"><%= image_tag ("icon-twitter.png"), :class => "footer-icons" %>
    </a>
    and fork me <a target="_blank" href="https://github.com/toywar" class="footer-icons"><%= image_tag ("icon-github.png"), :class => "footer-icons" %>
    </a>
</div>
<center>
<a href="/" class="footer-left">www.toywar.ru</a>
</center>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= bootstrap_form_for (@post) do |f| %>

      <div class="field">
        <p class="post-title" align="center"> Название:<br></p>
        <%= f.text_area :title, skip_label: true %>
      </div>
      <div class="field">
        <p class="post-title" align="center"> Текст:<br></p>
        <%= f.text_area :body, skip_label: true %>
      </div>
      <div class="field">
        <p class="post-title" align="center"> Дата/Время:<br></p>
        <%= f.datetime_select :date, skip_label: true %>
      </div>
      <div class="field">
        <p class="post-title" align="center"> Картинка для главной:<br></p>
        <%= f.text_field :image_url, skip_label: true %>
      </div>
      <div class="actions" style="text-align: center;">
        <%= f.submit "Сохранить", class: "btn btn-success" %>
        <%= link_to 'Назад', @post, class: "btn btn-warning" %>
      </div>
  <% end %>
<% end %>

app/views/posts/_header.html.erb
<% if session[:user_id] %>
    <%= render :partial => 'posts/navigation' %>
<% end %>
<center>
  <%= image_tag ("toywar.jpg"), :class => "img-circle" %><br/>
  <h1>IT::Sheets by <a target="_blank" class="top" href="https://twitter.com/toywar/" >@toywar</a></h1>
</center>

<p class="title-index">Привет! Здесь я храню различные IT-заметки.</p>
<hr class="dots" />

app/views/posts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">IT::Sheets [admin access]</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Посты", posts_url %></li>
        <li><%= link_to "Новый пост", new_post_url %></li>
        <li><%= link_to "Юзеры", users_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Выход", sessions_destroy_url %></li>
      </ul>

    </div>

  </div>
</nav>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2>
      <%= image_tag (post.image_url), :class => "img-circle" %>
      <%= link_to post.title, post, :class => "link-title-post" %>
      |
      <small><%= post.date.strftime("%d-%m-%Y в %H:%M") %></small>
    </h2>
    <%= will_paginate @posts, :class => "apple_pagination" %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p class="post-title"><%= @post.title %></p>

<p class="post-body"><%= @post.body %></p>

<p class="post-back"><%= link_to "Назад", posts_path, :class => "button-back" %>

<% if session[:user_id] %>
    <%= link_to "Редактировать", edit_post_path, :class => "button-back" %>
<% end %>

</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= bootstrap_form_for (@user) do |f| %>

  <div class="field">
    <p class="post-title" align="center">Юзернейм:</p>
    <%= f.text_field :name, skip_label: true %>
  </div>
  <div class="field">
    <p class="post-title" align="center">Пароль:</p>
    <%= f.password_field :password, skip_label: true %>
  </div>
  <div class="field">
    <p class="post-title" align="center">Повторите пароль:</p>
    <%= f.password_field :password_confirmation, skip_label: true %>
  </div>
  <div class="actions" align="center">
    <%= f.submit "Сохранить", class: "btn btn-success" %>
    <%= link_to 'Назад', users_path, class: "btn btn-warning" %>
  </div>
<% end %>
<% end %>

app/views/users/edit.html.erb
<h3 align="center">Редактирование юзера<br/> <span class="label label-danger"><%= @user.name %></span></h3>
<br>
<%= render 'form' %>
<br>
<p align="center">
</p>

app/views/users/index.html.erb
<h1 align="center">Юзеры</h1>

<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Юзернейм</th>
      <th>Показать</th>
      <th>Редактировать</th>
      <th>Грохнуть</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p align="center"> <%= link_to 'Новый юзер', new_user_path, class: "btn btn-success"%></p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<p class="post-back"> <%= link_to 'Назад', users_path, :class => "button-back" %></p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h4 align="center">Юзернейм: <span class="label label-success"><%= @user.name %></h4>
<h4 align="center">Пароль: <span class="label label-success"><%= @user.password_digest %></h4>
<br/>
<p align="center">
<%= link_to 'Редактировать', edit_user_path(@user), class: "button-back" %>
<%= link_to 'Назад', users_path, class: "button-back" %>
</p>